### ISSUE TITLE
single board

### ISSUE THREAD

**Issue by wickedanna** [kannmelton2/pinterest#9]
## USER STORY
As a user, when I click on one of my boards, I should see a single board view that shows all pins for that board.

## AC
WHEN a user clicks on one of their boards
THEN that should open the board to view all of the pins on it
AND that should be the only board a user sees
AND that board should show only the pins that have that board's id assigned to them

## DEV NOTES
- [x] add a `<div>` with an `id` of `single-view` to `index.html`
- [x] add an `id` to each `<div>` with a class of `card` using a template literal with the board's `id` found in the individual object
* Do this in the `boardComponent` file in the `boardMaker` function
- [x] attach an event listener using jquery in the `boards.js` file in the function called `buildBoards`
- [x] create a `pinData.js` file in the `src/javascripts/helpers/data` folder
- [x] import `axios`
- [x] import `apiKeys.json`
- [x] declare a variable called `baseUrl` that calls on `apiKeys.json` to get the value of the `databaseURL` key
- [x] create a function called `getPins`
- [x] `getPins` should take no arguments
- [x] creates a `new Promise` which takes the arguments `resolve` and `reject`
- [x] use `axios.get()` to retrieve information from the database
* use the link in the first comment below and look at the `getCows` function for reference
- [x] write `.then()` and `.catch()` to determine what the function does with the data
- [x] `.then()` should take an argument called `response`
- [x] declare a variable called `allPins` and give it a value of `response.data`
- [x] declare a second variable called `pins` which should be an empty array
- [x] use Object.keys and pass in `allPins`
- [x] use a`.forEach` to loop through `allPins`
- [x] use `pinId` as argument
- [x] use `allPins[pinId].id = pinId;` to move the pin's id into the object
- [x] then push the object into the `pins` array
- [x] `resolve(pins);` outside of the `.forEach`
- [x] write `.catch((err) => reject(err));`
- [x] export the function
- [x] create a new folder under `src/javascripts/components` called `singleBoard`
- [x] create a `singleBoard.js` and a `singleBoard.scss` file
- [x] import `utils` to `singleBoard.js`
- [x] import `pinData.js`
- [x] write a function called `singleBoardView`
- [x] declare a variable in the function called `boardId` and use `e.target.closest('.card').id` to get the correct id to display the single board view
- [x] use `pinData.getPins()`
- [x] use `.then()` and `.catch()`
- [x] `.then()` builds out the html for the single board view:
- [x] use a `.forEach()` to loop through the pins array
- [x] use a nested `.filter()` to grab all of the pins that have a boardId that matches the id of the board that was clicked
- [x] build out the html inside the `.forEach()`
- [x] use `utils` to clear everything in the other `<div>`s (outside of the `.forEach()`
* you may also try to use the `hide` class, but it may mess with the layout
- [x] use `utils` to print the html to the DOM (outside of the `.forEach()`)
- [x] `.catch()` consoles the error with a short string - something like `'problem with getPins'`
- [x] export `singleBoardView`
- [x] import `singleBoard` to `boards.js`
- [x] call it in the `buildBoards` function as an event listener using jquery

**Comment by kannmelton2** [comment]
https://github.com/kannmelton2/firebase-cows/blob/master/src/javascripts/helpers/data/farmerCowData.js

**Comment by wickedanna** [comment]
https://github.com/kannmelton2/firebase-cows/blob/master/src/javascripts/helpers/data/cowData.js

**Comment by wickedanna** [comment]
use an if statement instead of filter
